// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRO19WFgglELU_cUXoBgGCEC6vHwj0CA',
    appId: '1:356707026533:web:69a07e591fa3cc1689a88c',
    messagingSenderId: '356707026533',
    projectId: 'alq-galery',
    authDomain: 'alq-galery.firebaseapp.com',
    storageBucket: 'alq-galery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzYo_ZsHxxSgb5zwGRBlWul8vw1wrP1I',
    appId: '1:356707026533:android:049fbdcd4eda5a2289a88c',
    messagingSenderId: '356707026533',
    projectId: 'alq-galery',
    storageBucket: 'alq-galery.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHFxrrCUO5w5Ox99FVV7Wzveh7udTzEE',
    appId: '1:356707026533:ios:7c06c2d2b9b806d189a88c',
    messagingSenderId: '356707026533',
    projectId: 'alq-galery',
    storageBucket: 'alq-galery.firebasestorage.app',
    androidClientId: '356707026533-g1746io8r20hklmrim49d4ic4ik70ul9.apps.googleusercontent.com',
    iosClientId: '356707026533-311s6se851fbnetrfpnvh0sspc2apvur.apps.googleusercontent.com',
    iosBundleId: 'com.example.aGaleryApp',
  );
}
